@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
/'
    C4 context diagram guide

    Person(alias, label, ?descr, ?sprite, ?tags, ?link, ?type)
    Person_Ext(alias, label, ?descr, ?sprite, ?tags, ?link, ?type)
    System(alias, label, ?descr, ?sprite, ?tags, ?link, ?type, ?baseShape)
    SystemDb(alias, label, ?descr, ?sprite, ?tags, ?link, ?type)
    SystemQueue(alias, label, ?descr, ?sprite, ?tags, ?link, ?type)
    System_Ext(alias, label, ?descr, ?sprite, ?tags, ?link, ?type, ?baseShape)
    SystemDb_Ext(alias, label, ?descr, ?sprite, ?tags, ?link, ?type)
    SystemQueue_Ext(alias, label, ?descr, ?sprite, ?tags, ?link, ?type)
    Boundary(alias, label, ?type, ?tags, ?link, ?descr)
    Enterprise_Boundary(alias, label, ?tags, ?link, ?descr)
    System_Boundary(alias, label, ?tags, ?link, ?descr)
'/

/'Branch Appointment Scheduling System 
- A system for booking in-branch or virtual appointments with real-time staff availability 
    (e.g. home loans, financial advice).'/

Person_Ext("pe_customer", "Customer", "A customer of BankOne")

System_Ext("sys_external_identity", "External Authentication System", "An external system that allows BankOne to identify customers")

System_Boundary("BankOne", "BankOne System Landscape diagram", ) {
    /'people: Customers, Frontline staff, internal operations'/
    /'Systems: Identify, Payments, Risk, Notifications, Online Banking
        core banking system, customer management system, email system, payments system
    '/
    Person("p_staff", "Frontline Staff", "A call center or front counter staff member of BankOne")
    System("sys_online_staff_portal", "Web App Staff Portal System", "Allows staff to complete work tasks related to banking services and appointments")
    System("sys_online_banking", "Web App Banking Services System", "Allows customers to utilize online BankOne services")
    System("sys_ass","Branch Appointment Scheduling System", "allows for the creation, cancellation, or rescheduling of appointments to see frontline staff")
    System("sys_customer_management", "Customer Management System", "Stores customer information including contact details, authentication details, personal information","test")
    System("sys_staff_management", "Staff Management System", "Stores staff information including contact details, authentication details, personal information")
    System("sys_staff_availability", "Staff Availability System", "Stores real time staff availability information for appointments")
    System("sys_notifications", "Notifications System", "Allows BankOne to send notifications to customers and staff")
    System("sys_hr_management", "HR Management System", "Allows BankOne to manage employee information, rosters, and payroll")
}

/'customer relationships'/
Rel(pe_customer, sys_online_banking, "completes banking tasks with", "Web browser, mobile app")
Rel(pe_customer, p_staff, "Completes banking tasks with", "call centre, in person")
/'customer management system relationships'/
Rel(sys_customer_management, sys_external_identity, "Authenticates identity of customer with")
/'staff management system relationships'/
Rel(sys_staff_management, sys_external_identity, "Authenticates identity of staff member with")
/'Branch appointment relationships'/
Rel(sys_ass, sys_staff_availability, "Receives real time staff availability information from")
Rel(sys_ass, sys_notifications, "Sends appointment notifications to customers and staff with")
/'Web app banking services relationships'/
Rel(sys_online_banking, sys_ass, "Manages appointments using")
Rel(sys_online_banking, sys_customer_management, "provides customer data and services with")
/'Staff portal relationships'/
Rel(sys_online_staff_portal, sys_ass, "Manages appointments with")
Rel(sys_online_staff_portal, sys_staff_management, "provides staff data and services with")
Rel(sys_online_staff_portal, sys_staff_availability, "updates staff availability in real time with")
Rel(sys_online_staff_portal, sys_hr_management, "Updates employee information and rosters within")
/'notification system relationships'/
Rel(sys_notifications, p_staff, "Sends notifications to staff members")
Rel(sys_notifications, pe_customer, "Sends notifications to customers")
/'hr management system relationships'/
Rel(sys_hr_management, sys_staff_availability, "Updates staff availability information")

/'Frontline staff relationships
Rel(p_staff,"")
'/
Rel(p_staff,sys_online_staff_portal,"Uses staff portal to complete manage and complete work tasks")
@enduml